// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RevendaPedidos.Infrastructure.Migrations
{
    [DbContext(typeof(RevendaPedidosDbContext))]
    partial class RevendaPedidosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevendaPedidos.Domain.Entities.Revenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Revendas");
                });

            modelBuilder.Entity("RevendaPedidos.Domain.Entities.Revenda", b =>
                {
                    b.OwnsMany("RevendaPedidos.Domain.Entities.Contato", "Contatos", b1 =>
                        {
                            b1.Property<Guid>("RevendaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<bool>("Principal")
                                .HasColumnType("bit");

                            b1.HasKey("RevendaId", "Nome");

                            b1.ToTable("Contato");

                            b1.WithOwner()
                                .HasForeignKey("RevendaId");
                        });

                    b.OwnsMany("RevendaPedidos.Domain.Entities.EnderecoEntrega", "EnderecosEntrega", b1 =>
                        {
                            b1.Property<Guid>("RevendaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nome")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RevendaId", "Nome");

                            b1.ToTable("EnderecoEntrega");

                            b1.WithOwner()
                                .HasForeignKey("RevendaId");
                        });

                    b.OwnsMany("RevendaPedidos.Domain.Entities.Telefone", "Telefones", b1 =>
                        {
                            b1.Property<Guid>("RevendaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Numero")
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("RevendaId", "Numero");

                            b1.ToTable("Telefone");

                            b1.WithOwner()
                                .HasForeignKey("RevendaId");
                        });

                    b.Navigation("Contatos");

                    b.Navigation("EnderecosEntrega");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
